services:
  Upspinner\ConnectBundle\Transport\UpspinnerMailerTransportFactory:
    tags:
      - { name: mailer.transport_factory }

  Upspinner\ConnectBundle\Transport\UpspinnerNotifierTransportFactory:
    parent: notifier.transport_factory.abstract
    tags:
      - { name: texter.transport_factory }

