name: Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: 8.1
      - uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
      - uses: php-actions/phpstan@v3
        with:
          php_version: 8.1
      - uses: php-actions/phpunit@v3
        with:
          php_version: 8.1
